# Generated by Django 4.0.3 on 2022-03-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='created_by',
        ),
    ]
