# Generated by Django 4.0.3 on 2022-03-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('firstname', 'lastname')},
        ),
    ]
