# Generated by Django 4.0.3 on 2022-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_author_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_list', to='api.author'),
        ),
    ]
