# Generated by Django 4.0.3 on 2022-03-23 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_author_created_by_publisher_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='1', help_text='Autor', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(default='', help_text='Wydawnictwo', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True, help_text='Komentarz użytkownika do książki', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data i czas utworzenia pozycji'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(editable=False, help_text='Użytkownik, który utworzył pozycję', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_number',
            field=models.PositiveIntegerField(blank=True, help_text='Nr wydania książki', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, help_text='Rok publikacji', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Tytuł', max_length=512),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
