# Generated by Django 4.0.3 on 2022-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_publisher_created_by_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ocena użytkownika', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'do przeczytania'), (1, 'w trakcie'), (2, 'przeczytana')], help_text='Status książki', null=True),
        ),
    ]
