# Generated by Django 4.0.3 on 2022-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_book_rate_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Ocena użytkownika'),
        ),
    ]
