# Generated by Django 4.0.3 on 2022-04-14 20:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.ImageField(blank=True, help_text='Okładka książki', null=True, upload_to=api.models.upload_to),
        ),
    ]
