# Generated by Django 4.0.3 on 2022-04-15 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='cover',
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Ocena użytkownika', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
