# Generated by Django 4.0.3 on 2022-04-15 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_rename_image_url_book_cover_alter_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Ocena użytkownika (min=0, max=5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'do przeczytania'), (1, 'w trakcie'), (2, 'przeczytana')], help_text='Status książki: 0-do przeczytania, 1-w trakcie, 2-przeczytana', null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_to_read', models.TextField(blank=True, help_text='Planuję przeczytać', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
