# Generated by Django 4.0.3 on 2022-04-15 20:19

from django.db import migrations
from django.contrib.auth.models import User
from api.models import Profile


def make_profiles(apps, schema_editor):
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_book_rate_alter_book_status_profile'),
    ]

    operations = [
        migrations.RunPython(make_profiles),
    ]
