# Generated by Django 4.0.3 on 2022-04-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220415_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='auth_user_profile',
        ),
    ]
